# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_pad_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
