# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_pad_app', '0002_auto_20170709_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
